"""empty message

Revision ID: 0afddd2bad7d
Revises: da22a331a250
Create Date: 2018-06-06 15:57:54.223897

"""

# revision identifiers, used by Alembic.
revision = '0afddd2bad7d'
down_revision = 'da22a331a250'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('wbso', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'wbso')
    # ### end Alembic commands ###
