"""empty message

Revision ID: c8f4b08529a4
Revises: bbd324935815
Create Date: 2017-05-02 00:04:57.131824

"""

# revision identifiers, used by Alembic.
revision = 'c8f4b08529a4'
down_revision = 'bbd324935815'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entries', 'users', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_column('entries', 'user_id')
    # ### end Alembic commands ###
