"""empty message

Revision ID: da22a331a250
Revises: c8f4b08529a4
Create Date: 2018-06-06 15:14:55.773963

"""

# revision identifiers, used by Alembic.
revision = 'da22a331a250'
down_revision = 'c8f4b08529a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('ticket', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'ticket')
    # ### end Alembic commands ###
