"""empty message

Revision ID: ed386a3504a8
Revises: 2d69702d4892
Create Date: 2019-02-06 15:25:13.096699

"""

# revision identifiers, used by Alembic.
revision = 'ed386a3504a8'
down_revision = '2d69702d4892'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
