"""empty message

Revision ID: ed386a3504a8
Revises: 2d69702d4892
Create Date: 2019-02-06 15:25:13.096699

"""

# revision identifiers, used by Alembic.
revision = 'z'
down_revision = 'ed386a3504a8'

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('pmc', sa.String(50), default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'pmc')
    # ### end Alembic commands ###
